### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by adrianheine** [othree/jquery.rtl-scroll-type#4]
The demo alerts `negative` for Firefox, Chromium and Webkit2-based Epiphany. Chromium should be `default`.

**Comment by othree** [comment]
My chromium shows 'default'

![2017-04-25 5 58 14](https://cloud.githubusercontent.com/assets/16474/25380005/4eaec4cc-29e1-11e7-9e93-92cc78e8868e.png)

**Comment by adrianheine** [comment]
I'm running Chromium 58 on Debian. I get `default` with a `width` greater or equal `4px`.

**Comment by othree** [comment]
Chromium should be `default`. That's correct as README describes.

**Comment by adrianheine** [comment]
Yeah, but I only get it with a `definer` `width` `>=4px`, with `1px` to `3px`, it's `negative`.

**Comment by othree** [comment]
Not sure why this happens.
Sorry I don't have a Linux desktop.
What I can do now is update the definer‘s style.
And set it give more strictly.

**Comment by phistuck** [comment]
In the future, please, file a bug against Chrome instead of (or in addition to) fixing it. Those changes are usually not intended (and if they are, the bug will simply be closed, no biggie).
https://bugs.chromium.org/p/chromium/issues/detail?id=720227 was filed and the root cause seems to be this scroll type detection difference, so no need to file a bug for this now.

Thank you in advance!

**Comment by fred-wang** [comment]
@othree I understand this regression was due to scrollbars. Maybe it would be better to use `overflow: hidden` to avoid these kind of issues. This is what my example in #6 does.
